### ISSUE TITLE
Dashboard-Profile Creation failing

### ISSUE THREAD

**Issue by satya-gorli** [opensds/opensds-dashboard#101]
1. Click Profile Menu
2. Fill Fields in Create Volume Page
3. Click Submit
4. 502 Bad Gateway error coming..

**Comment by leonwanghui** [comment]
I think the latest code works fine for issues you mentioned, could u take a check?

**Comment by himanshuvar** [comment]
Issue is with the nginx mapping

**Comment by anvithks** [comment]
@satya-gorli Please test this with the latest code and let us know if the issue persists.
502 errors are usually encountered on a bad network connection, overloaded network or when the osdsapiserver is not running.

**Comment by satya-gorli** [comment]
Latest its working fine
