### ISSUE TITLE
Didn't see alert manager and grafana link or page

### ISSUE THREAD

**Issue by wisererik** [opensds/opensds-dashboard#102]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

![Selection_011](https://user-images.githubusercontent.com/9572954/59286911-38574980-8c8e-11e9-9f42-73bcce417ca7.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Dashboard(release/branch) version: latest image
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by anvithks** [comment]
@skdwriting Needs to be fixed.

**Comment by anvithks** [comment]
Fixed in #93.
