### ISSUE TITLE
Orchestration-Dashboard- Services are not visible

### ISSUE THREAD

**Issue by satya-gorli** [opensds/opensds-dashboard#106]
1. after following installation steps, send servie requests throug Postman
2. those services should be displayed in Dashboard-> Services tabl
3. No services getting displayed
4. Issue is with Port mapping in nginx config file

**Comment by anvithks** [comment]
@satya-gorli This is due to the nginx configuration not being updated.  
The orchestration api server is running at the same path /v1beta but on a different port.  
The nginx configuration has to be updated and the url has to be rewritten to point to the appropriate end point:port mapping.

**Comment by anvithks** [comment]
@satya-gorli This is not an issue on the dashboard repository. Suggest you raise an issue on the installer and cross close when fixed.

**Comment by anvithks** [comment]
@skdwriting Needs to be fixed.

**Comment by satya-gorli** [comment]
Root cause can be anything.. As end user perspective, in Dashboard its not shown..Once fixed, let me know.. will verify and close
