### ISSUE TITLE
Dashboard-Resource: Same Description is shown for Bucket, Volume, VolumeGroup... in REsource Menu 

### ISSUE THREAD

**Issue by satya-gorli** [opensds/opensds-dashboard#108]
1 Click REsource Menu
2. Click on each Tabs .. Bucket, Volume, Volume Grp...
3. Same description is shown..
4. Should show description about the clicked tab-feature
 or.. if the description is about Resource Menu.. it should be above the Tabs
![Resource-dashboard-Same Description for all tabs](https://user-images.githubusercontent.com/48289385/59405500-48734400-8dc8-11e9-82e9-cece3474fe60.PNG)

**Comment by skdwriting** [comment]
@satya-gorli , please comment on the expected behavior as well...

**Comment by satya-gorli** [comment]
expected Behavior:
Should show description about the clicked tab-feature
and.. if the description to be given about Resource Menu.. it should be above the Tabs

**Comment by anvithks** [comment]
@satya-gorli  We have made the following change:  
**Buckets**: View and manage Buckets that have been manually created or applied for through service templates.  
**Volumes**: View and manage Volumes that have been manually created or applied for through service templates.  
**Volume Groups**: View and manage Volume Groups that have been manually created or applied for through service templates.  
 **File Share**: View and manage File Shares that have been manually created or applied for through service templates.
