### ISSUE TITLE
Dashboard hungs and will be in loop forever - because of nginx: [emerg] bind() to 192.168.56.102:80 failed (98: Address already in use)

### ISSUE THREAD

**Issue by Shruthi-MN** [opensds/opensds-dashboard#109]
**Describe the bug**
Dashboard hungs and will be in loop forever - because of nginx: [emerg] bind() to 192.168.56.102:80 failed (98: Address already in use).

**To Reproduce**
1. Follow the steps in https://github.com/opensds/opensds/wiki/OpenSDS-Cluster-Installation-through-Ansible
2. No extra steps needed to recreate this issue
3. Find logs as mentioned below for errors
4. docker container ls - we can find dashboard container is restart loop

**Expected behavior**
Able to open gui with opensds end point host
create volume through cli

**Screenshots**
Not able to set endpoints - dashboard is not up 
osdctl pool list - from cli - throws 404 error 

I am pasting all logs below

root@leo-VirtualBox:~# docker container ls
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                         PORTS               NAMES
aa3f423d1742        opensdsio/dashboard:latest   "/bin/sh -c /opt/das…"   4 days ago          Restarting (1) 2 seconds ago                       dashboard

root@leo-VirtualBox:~# docker inspect -f "{{.Name}} {{.Config.Cmd}} {{.Args}}" $(docker ps -a -q) 
/opensds-gelato-linux-amd64_datamover_1_1da42328c821 [] []
/opensds-gelato-linux-amd64_dataflow_1_53df5bc6632a [] []
/opensds-gelato-linux-amd64_kafka_1_2910f560669c [start-kafka.sh] []
/opensds-gelato-linux-amd64_s3_1_54e1105f23ec [] []
/opensds-gelato-linux-amd64_api_1_830f09420f51 [] []
/opensds-gelato-linux-amd64_zookeeper_1_f6ab3615af3f [/bin/sh -c /usr/sbin/sshd && bash /usr/bin/start-zk.sh] [-c /usr/sbin/sshd && bash /usr/bin/start-zk.sh]
/opensds-gelato-linux-amd64_datastore_1_b05b2810b7df [mongod] [mongod]
/opensds-gelato-linux-amd64_backend_1_2b46352abd0b [] []
/dashboard [] [-c /opt/dashboard/entrypoint.sh]
root@leo-VirtualBox:~# find / -name dashboard
find: ‘/run/user/1000/gvfs’: Permission denied
/var/lib/docker/overlay2/d5a01404396909eca47a233f1cfbb836a8a3971ebe37d8033488f57c35079dfb/diff/opt/dashboard
/var/lib/docker/overlay2/6a4ae1b76eeca61f76d5b3132ff880831f84e4160e905ae53b94e210aa8b83ab/diff/opt/dashboard
/var/lib/docker/overlay2/245fd025b3a617db229f7648c7a5e077842ff1d56ce73b8d3f209d802838e171/diff/opt/dashboard
/var/lib/docker/overlay2/7fe8e099b5efd788d16c27efe5e22208629f461434e0f1462d157de596d62475/diff/opt/dashboard
root@leo-VirtualBox:~# ls -ltr /var/lib/docker/overlay2/d5a01404396909eca47a233f1cfbb836a8a3971ebe37d8033488f57c35079dfb/diff/opt/dashboard
total 484
-rwxr-xr-x   1 root root    860 Jan 30 08:58 image_builder.sh
-rw-r--r--   1 root root 450052 Jan 30 09:04 package-lock.json
drwxr-xr-x 897 root root  36864 Jan 30 09:08 node_modules
drwxr-xr-x   4 root root   4096 Jan 30 09:08 dist
root@leo-VirtualBox:~# ls -ltr /var/lib/docker/overlay2/6a4ae1b76eeca61f76d5b3132ff880831f84e4160e905ae53b94e210aa8b83ab/diff/opt/dashboard
total 4
-rwxr-xr-x 1 root root 1348 Jan 30 08:58 entrypoint.sh
root@leo-VirtualBox:~# ls -ltr /var/lib/docker/overlay2/245fd025b3a617db229f7648c7a5e077842ff1d56ce73b8d3f209d802838e171/diff/opt/dashboard
total 512
-rw-r--r-- 1 root root   3040 Dec  4 13:13 tslint.json
-rw-r--r-- 1 root root    471 Dec  4 13:13 tsconfig-release.json
-rw-r--r-- 1 root root    385 Dec  4 13:13 tsconfig.json
-rw-r--r-- 1 root root    548 Dec  4 13:13 tsconfig-aot.json
drwxr-xr-x 5 root root   4096 Dec  4 13:13 src
-rw-r--r-- 1 root root   1945 Dec  4 13:13 README.md
-rw-r--r-- 1 root root    290 Dec  4 13:13 proxy.conf.json
-rw-r--r-- 1 root root    722 Dec  4 13:13 protractor.conf.js
-rw-r--r-- 1 root root 447534 Dec  4 13:13 package-lock.json
-rw-r--r-- 1 root root   2148 Dec  4 13:13 package.json
-rw-r--r-- 1 root root   1079 Dec  4 13:13 LICENSE.md
-rw-r--r-- 1 root root   1056 Dec  4 13:13 karma.conf.js
-rw-r--r-- 1 root root   1675 Dec  4 13:13 gulpfile.js
drwxr-xr-x 2 root root   4096 Dec  4 13:13 exports
drwxr-xr-x 2 root root   4096 Dec  4 13:13 e2e
-rw-r--r-- 1 root root   1072 Dec 18 09:06 Makefile
-rwxr-xr-x 1 root root    860 Jan 30 08:58 image_builder.sh
-rwxr-xr-x 1 root root   1348 Jan 30 08:58 entrypoint.sh
-rw-r--r-- 1 root root   1300 Jan 30 08:58 Dockerfile
root@leo-VirtualBox:~# ls -ltr /var/lib/docker/overlay2/7fe8e099b5efd788d16c27efe5e22208629f461434e0f1462d157de596d62475/diff/opt/dashboard
total 0
root@leo-VirtualBox:~# ls -ltr /var/lib/docker/overlay2/7fe8e099b5efd788d16c27efe5e22208629f461434e0f1462d157de596d62475/diff/opt/ |grep dashboard
drwxr-xr-x 2 root root 4096 Dec 25 08:46 dashboard
root@leo-VirtualBox:~# uname -a
Linux leo-VirtualBox 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
root@leo-VirtualBox:~# cd opensds-installer/ansible/

Tried to clean docker images still not useful to remove dashboard container for fresh restart
root@leo-VirtualBox:~/opensds-installer/ansible# docker system prune -a
WARNING! This will remove:
        - all stopped containers
        - all networks not used by at least one container
        - all images without at least one container associated to them
        - all build cache
Are you sure you want to continue? [y/N] y
Deleted Containers:
a357017aff1766666c1c4a828c487807d1827d8a9529f6ae973d326b3bcdb245
e29327834d5a499819aa3653aa0f2a43d4825c7ab02eedc3fe7907b20a94b91b
b13e636f8b1bd900ba86ccc8db896695ef8b9b7ec2deff8f5b72d8df22cce7c9
b9d884c73e8c644145599b9bae900eb5f09949887b930a8d7d0185d414f70d1b
ce8833afe7480333936acdf8c622dee078a5994487da1472f37e511c95ded858
943712d1c25e94d6021ef43811ae6adff84d4267c439dc2ceb1089273493dc1b
ff7a26ad6d5db4787509ef86cdb8cc5ef7528d83b91d0b98a28e7fe51efc54cb
8461ff4ec3e179b026414362983a6b2ef6a09497a21cb0800861c6692f6bd3c8

Deleted Networks:
opensds-gelato-linux-amd64_default

Deleted Images:
untagged: wurstmeister/zookeeper:latest
untagged: wurstmeister/zookeeper@sha256:7a7fd44a72104bfbd24a77844bad5fabc86485b036f988ea927d1780782a6680
deleted: sha256:3f43f72cb2832e7a5fbed7f7dbcd0c43004357974d8f32555d101bd53e81e74f
deleted: sha256:9400d250553da456c2a6a0a1a2b623187f4cec74a82d06b5ba92ed62d733a29c
deleted: sha256:2ff9c39e52230513a800779cc1ba965ba859d187fd16148087f1cd6acee2a4b3
deleted: sha256:489d1513a6493c400fa74fda18fd50d2bc6fbe12b7f117b944f57189ba15f8ee
deleted: sha256:eda046764f032d0b0a991338f53e4f458fdb9b7cdd559026d1ee89f8f4359c00
deleted: sha256:e7c0f286e644475ea4736293fc07c39beb36305cf5311a122fb46e166cf34959
deleted: sha256:54b257a71928bb723fbfe4eb5083cc7dd1e0c78ab2ec2b82d47cafce2b1e5af7
deleted: sha256:feb06b3539913d2c817a6a4aa15ce87925ec57e87fe001fdb21e19a4dc34205c
deleted: sha256:8a0be0ba98a0a5645b5d23bed652380aec4a501b0136854bf6979ef3652b9a8a
deleted: sha256:69914bc13886a16f82d734f05b6d31535e32578b0b8027ecd0876f7eee226195
deleted: sha256:0a6a558061d2753ff3d7a3b2f699b4141afa286c46c64d7479c70680ffb3b31c
deleted: sha256:16aae303a3e3fc8a3fa161fb753ac18df7fb5cdc3d118bbb1edceb86d846f7ed
deleted: sha256:d20413971c378e688f6981c69378d2dbf146dce8c69e3281e38b03ff181d8064
deleted: sha256:0f72e5b180fabc7d295dd2a09fea1b629c83eb6bd13d2e640716251cdbcb3094
deleted: sha256:1020c0c0f4edc7a5b695351d2dcb8c4e9d70ebd4366d17574ca7e27dfe543fdf
deleted: sha256:ee468bb36d6d7ef3483378dff5c7920a1340b1e4f5f8c54158d1098e04b79f63
deleted: sha256:b94a4e48c2c794072e2311cf565a05b12fcff9ab097a294fc57ed9110fd90795
deleted: sha256:a94a7b5aa8b29d57798c38c7245945c812febe492107770ba965b154d86e869f
deleted: sha256:9297f600c87d20c6baa252eb509ba3ed6704804237d9d8feec34ddd4ec99184b
deleted: sha256:f4808639fed5aa49d2b3250683b566a96bdd6652fb0f91ff9024fa0ab89a6bc4
deleted: sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef
untagged: opensdsio/multi-cloud-api:latest
untagged: opensdsio/multi-cloud-api@sha256:76f98d7937f36623bd97a49a2c7640b11ad783ba16eed59115191ba03ec640ff
deleted: sha256:40bd58b293d3645591a8a08c0cb8b8fb0ae039380ed01efe98c8cd1683eff58e
deleted: sha256:311418d2a5efb4d0c4532b486f4f4a29a7dfb647d0d88c4f69bf9a8f62d2319d
deleted: sha256:e67564ff9601a598060c9d58273db6638fd2a0061184c35985abbe16b19cce7f
deleted: sha256:a5ea4bd2ddc16a09d18bcfb58588ab9a1806747c36ef61d6ef7a555752275b67
untagged: opensdsio/multi-cloud-s3:latest
untagged: opensdsio/multi-cloud-s3@sha256:ab970c10d8073b70215e62f486595006479e6a8d717449b9977e2f1eabfdd43e
deleted: sha256:40c533bf0cee733d394c79fea812b92a8b50f89c0b553aa2bca78ec1bd481ee2
deleted: sha256:5b8c6231e0d257789e379e500cf9b7862f53da5c53fb316717a4860a31cf45d6
untagged: wurstmeister/kafka:2.11-2.0.1
untagged: wurstmeister/kafka@sha256:20d08a6849383b124bccbe58bc9c48ec202eefb373d05e0a11e186459b84f2a0
deleted: sha256:0a31db789bfd225f97a7a4731d83320d15c97aee6e27e6cc2f78397c49366aa1
deleted: sha256:11ffa9a1e1f97f65180fab0d32751283dd6572060118affa57268495a6a4a414
deleted: sha256:8295633892df8f757d3737d5569df64b8519d4bad06796c5d06e30ed7d6127f6
deleted: sha256:bb7e6e2ce1304ffa350b6ec83cb0faf1ea9f61ac9c6610c9843970f5889fec3a
deleted: sha256:5b98423ee68b954601a93be494cbf128034a3db73e9bba86dfbccb3487ca3758
deleted: sha256:577174891c779d8b287b2132bfc1335f435f6b167716fdc410c6645a37b37ab2
untagged: mongo:latest
untagged: mongo@sha256:809b0e46ff69d67c4fef05954f45479d2d97b92834b39033660fb0c07144c525
deleted: sha256:0da05d84b1fe3b5620c55bf254446fc052e28ccd53d320954fbc593ab701204b
deleted: sha256:50817c356899c50ca88f166ed57867b91aa8aa983c682fbcd29d2ff0ffef0d41
deleted: sha256:c59bc92f4bb6a75b47414b511981325fcf1ef7771ae662af4dd56e2b5885e994
deleted: sha256:d59e03c9a4fe7075fc8c516543f7980c656784618253e83f70a7e28f363a0149
deleted: sha256:295f8f2f200059ea7b371c902df690d013726ec028d07532258c5d8e59507e29
deleted: sha256:a1da0bb390d355b962d61bfd3ebf9e4bc5ea97b9da9b567641f9265dd4022cf4
deleted: sha256:5c15a1ac89ccbde361b909d57e67b31dfe351202e7f35bb42987b946bd57f084
deleted: sha256:65139472fcd9956c0da10d08473923afef380d559f5fca6374ceef28436536a6
deleted: sha256:5fded825ac7bf50d4202e414fa3788ad483f67f1561b6bec463f57c8c559422e
deleted: sha256:64afd1cfa675af97141be6eed4456e9581357429ef64ae810471fd2755016055
deleted: sha256:7eb46ebc736921ffa70c8757618b02e4d0d3c4627d823a7e1b8f59bb924ecf93
deleted: sha256:4f9c6186221ca469b29e4b55599f2a7969b705df4ef10d1585f2e7681503eb7b
deleted: sha256:fc94d17b18c9a353a5b5b9500e04a4c24d8d4b2632fd549596c85e6157377fc2
deleted: sha256:0de2edf7bff41238438e25b6f2de055b97c7fb6fe095cd560c2095b8dd70fc99
untagged: opensdsio/multi-cloud-dataflow:latest
untagged: opensdsio/multi-cloud-dataflow@sha256:19c2319990f879614c4116c6773bb813c55ee855356a37bb4bf27c683c5ef8a7
deleted: sha256:9634dc05ed7c9d7c9ae94034eb432ab066a847d15176a07282e61931f9992a06
deleted: sha256:269b8204075488436bc765748fdfdcbaaf7cb1c3e8a9ecf13d10dc59aa8737fc
untagged: opensdsio/multi-cloud-backend:latest
untagged: opensdsio/multi-cloud-backend@sha256:1120397317d5706ff68ca2223c3a9f82152bee1ae8051ddc0b44b14e4f8cbfa3
deleted: sha256:97535caebf739539fbe6143de1707fa261733ab26271b9b5421ff2aff47c6159
deleted: sha256:c839763fe563ef11dc6ecefce746558191ad747cb2f602df3f20227d5487aac4
untagged: opensdsio/multi-cloud-datamover:latest
untagged: opensdsio/multi-cloud-datamover@sha256:d2d4bafd402789dec66e1dcd33c3c6ba41a55825220d8f4d5672375ad8812269
deleted: sha256:591226cdddedc190110a62ad4bc8bae094d3cf586975e80b5f6b7fe8b0156da0
deleted: sha256:04af277951272bb194d08baf0c9f87ee8df190055ac2a0be2f01cf003940cba5
deleted: sha256:df64d3292fd6194b7865d7326af5255db6d81e9df29f48adde61a918fbd8c332

Total reclaimed space: 1.347GB
root@leo-VirtualBox:~# docker images -a
REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
opensdsio/dashboard               latest              e99624a25a62        2 weeks ago         758MB
wurstmeister/zookeeper            latest              3f43f72cb283        4 weeks ago         510MB
opensdsio/multi-cloud-s3          latest              40c533bf0cee        5 weeks ago         20.5MB
opensdsio/multi-cloud-api         latest              40bd58b293d3        5 weeks ago         29.7MB
opensdsio/multi-cloud-datamover   latest              591226cddded        2 months ago        31.4MB
opensdsio/multi-cloud-dataflow    latest              9634dc05ed7c        2 months ago        23.3MB
opensdsio/multi-cloud-backend     latest              97535caebf73        2 months ago        20.3MB
wurstmeister/kafka                2.11-2.0.1          0a31db789bfd        3 months ago        339MB

root@leo-VirtualBox:~# docker images -f dangling=true
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
root@leo-VirtualBox:~# docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                          PORTS               NAMES
aa3f423d1742        opensdsio/dashboard:latest   "/bin/sh -c /opt/das…"   4 days ago          Restarting (1) 44 seconds ago                       dashboard
root@leo-VirtualBox:~# docker images purge
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
root@leo-VirtualBox:~# docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                          PORTS               NAMES
aa3f423d1742        opensdsio/dashboard:latest   "/bin/sh -c /opt/das…"   4 days ago          Restarting (1) 45 seconds ago                       dashboard
root@leo-VirtualBox:~# docker container rm aa3f423d1742
Error response from daemon: You cannot remove a restarting container aa3f423d174292a0bec07c3979e9e4c7ddc73f94df06c025c2b4aa84ec617701. Stop the container before attempting removal or force remove
root@leo-VirtualBox:~# ls -ltr /var/lib/docker/overlay2/245fd025b3a617db229f7648c7a5e077842ff1d56ce73b8d3f209d802838e171/diff/opt/dashboard^C
root@leo-VirtualBox:~# docker stop -t 10 container dashboard
dashboard
Error response from daemon: No such container: container
root@leo-VirtualBox:~# docker stop -t 60 container dashboard
dashboard
Error response from daemon: No such container: container
root@leo-VirtualBox:~# docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                              PORTS               NAMES
aa3f423d1742        opensdsio/dashboard:latest   "/bin/sh -c /opt/das…"   4 days ago          Restarting (1) About a minute ago                       dashboard
root@leo-VirtualBox:~# service nginx status
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-02-18 11:08:05 IST; 4h 14min ago
  Process: 793 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)
root@leo-VirtualBox:~# journalctl -xe
root@leo-VirtualBox:~# journalctl -xe
-- Unit nginx.service has begun starting up.
Feb 18 15:22:46 leo-VirtualBox nginx[4410]: nginx: [emerg] bind() to 192.168.56.102:80 failed (98: Address already in use)
Feb 18 15:22:46 leo-VirtualBox nginx[4410]: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
Feb 18 15:22:46 leo-VirtualBox nginx[4410]: nginx: [emerg] bind() to 192.168.56.102:80 failed (98: Address already in use)
Feb 18 15:22:46 leo-VirtualBox nginx[4410]: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
Feb 18 15:22:47 leo-VirtualBox nginx[4410]: nginx: [emerg] bind() to 192.168.56.102:80 failed (98: Address already in use)
Feb 18 15:22:47 leo-VirtualBox nginx[4410]: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
Feb 18 15:22:47 leo-VirtualBox nginx[4410]: nginx: [emerg] bind() to 192.168.56.102:80 failed (98: Address already in use)
Feb 18 15:22:47 leo-VirtualBox nginx[4410]: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
Feb 18 15:22:48 leo-VirtualBox nginx[4410]: nginx: [emerg] bind() to 192.168.56.102:80 failed (98: Address already in use)
Feb 18 15:22:48 leo-VirtualBox nginx[4410]: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
Feb 18 15:22:48 leo-VirtualBox nginx[4410]: nginx: [emerg] still could not bind()
Feb 18 15:22:48 leo-VirtualBox systemd[1]: nginx.service: Control process exited, code=exited status=1
Feb 18 15:22:48 leo-VirtualBox systemd[1]: Failed to start A high performance web server and a reverse proxy server.
-- Subject: Unit nginx.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit nginx.service has failed.
-- 
-- The result is failed.
Feb 18 15:22:48 leo-VirtualBox systemd[1]: nginx.service: Unit entered failed state.
Feb 18 15:22:48 leo-VirtualBox systemd[1]: nginx.service: Failed with result 'exit-code'.

**Desktop (please complete the following information):**
 - OS: ubuntu 16.04
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Shruthi-1MN** [comment]
I tested today. Dashboard doesn't hung now.
