### ISSUE TITLE
StorageType didn't show when creating a profile in dashboard

### ISSUE THREAD

**Issue by leonwanghui** [opensds/opensds-dashboard#125]
When I tried to deploy latest version of dashboard image to create a new profile, it seems that storageType field is missing as below:
![image](https://user-images.githubusercontent.com/24707117/59553922-c0ab5680-8fce-11e9-92ab-d6b0f18a493a.png)

**Comment by anvithks** [comment]
@leonwanghui Do you still have this environment running? 
I would like to take a look.

**Comment by anvithks** [comment]
@leonwanghui This is from a fresh install with latest code. I am not able to recreate the issue.
Please let me know if you are able to recreate this issue on a fresh install.
![create-profile-storage-type](https://user-images.githubusercontent.com/19162717/59560408-2c251080-902f-11e9-9628-4cdc239731d3.png)

**Comment by anvithks** [comment]
@leonwanghui I have checked this in the env provided by you and could not replicate this issue.
There are bunch of 502 Bad Gateway errors though. May be this was due to some network issue or a bad api call.

**Comment by leonwanghui** [comment]
Confirmed it's not an issue, closing this one
