### ISSUE TITLE
Dataflow: Migrations-> Newly created could be added to the top of the list?

### ISSUE THREAD

**Issue by skdwriting** [opensds/opensds-dashboard#132]
Newly added migration flow is added at the end. If its already at pagination limit, it may go to the next page and not visible in the first view.

Can we add the newly created to the top of the list?

**Comment by anvithks** [comment]
@skdwriting this makes sense. We will check and make this change.
@jimccfun Could you please take a look in this. Seems like a simple sort by latest should work.

**Comment by jimccfun** [comment]
@skdwriting @anvithks I'll make the change, thank you.
