### ISSUE TITLE
orchestration: in volume provisioning page, profile should only list block storage type.

### ISSUE THREAD

**Issue by PravinRanjan10** [opensds/opensds-dashboard#151]
orchestration: in volume provisioning page, profile should only list block storage type.Currently it is also showing the file storage type profile.

**Comment by anvithks** [comment]
@jimccfun Please have a look.

**Comment by jimccfun** [comment]
@anvithks 
![OZM}%)2U8DZ@(X)54ZN$W(K](https://user-images.githubusercontent.com/37950702/59913008-e65eb280-9449-11e9-9721-2edfb3790a70.png)
PRAVIN means here, profile should only list block storage type.

**Comment by anvithks** [comment]
Oh ok. Sure I will take a look at this.
