### ISSUE TITLE
FileShare-Dashboard: Snapshot name validation not done

### ISSUE THREAD

**Issue by satya-gorli** [opensds/opensds-dashboard#158]
1. create File share with in Available state
2. Create snapshot with special characters and lenghy text ( more than 300 chars)
3. System allowing to create snapshot
4. No validation at Client side and no validation at server side
5. Dashboard look is not good with such lengthy text
![FileShare_Snapshot_validation_name_2](https://user-images.githubusercontent.com/48289385/60094922-fbe61c00-976a-11e9-9706-461ec53edb38.PNG)

Expected behavior:
1. Client side validation and server side validation should be done for name for lenght and special characters
2. Dashboard should look normal with lenghty text also

**Comment by anvithks** [comment]
@PravinRanjan10 @Shruthi-1MN Please provide the validations for the fields in the file share APIs. We will incorporate the same in the dashboard.

**Comment by jimccfun** [comment]
@satya-gorli This will be fixed later
