### ISSUE TITLE
FileShare-DashBoard: Snapshot creation with huge description, error message is wrong

### ISSUE THREAD

**Issue by satya-gorli** [opensds/opensds-dashboard#159]
1. Create Fileshare with state Available
2. Create Snapshot page provide huge description (more than 300 chars)
3. Error in UI is shown as [Object, Object]
![FileShare_Snapshot_validation1](https://user-images.githubusercontent.com/48289385/60095259-c1c94a00-976b-11e9-8aa0-1f8cedbf0bdb.PNG)

Expected Behavior:
1. Proper error message should be displayed

**Comment by jimccfun** [comment]
@satya-gorli This will be fixed later
