### ISSUE TITLE
Support Storage Server Encryption on bucket from dashboard

### ISSUE THREAD

**Issue by rhsakarpos** [opensds/opensds-dashboard#199]
Support various Storage Server Encryption methods like:  
- SSE-C  
- SSE-KMS  
- CKM

Related to [opensds/multi-cloud #685](https://github.com/opensds/multi-cloud/issues/685)

**Comment by anvithks** [comment]
After discussion with @rhsakarpos and @kumarashit the scope for the SSE is finalised and the same is being integration tested. PR will be raised shortly

**Comment by anvithks** [comment]
PR is raised as WIP #211 this has versioning as well. Since the scope of versioning is now changed I will remove the versioning code from here and raise a separate PR. This PR will be updated on 22/11/19 after integration test with @rhsakarpos
