### ISSUE TITLE
Support refactored OpenSDS Hotpot  Provisioning APIs

### ISSUE THREAD

**Issue by anvithks** [opensds/opensds-dashboard#206]
The Hotpot APIs are being refactored and updated from OpenAPI spec 2.0 to 3.0.  
Alongwith that there are a few parameter changes to make the APIs more efficient and provide more control. 
These changes will have an impact on the Dashboard and how some of the fields are used (or not used) from the API responses.   
The first set of changes is in the Provisioning APIs:  
- Profiles  
- Pools 
- Volumes
Reference Link: [Click here](https://docs.google.com/document/d/1huHIIZQbjbnw1qSFmUsi0ER_vBuVbtDjHNpMcd9h9Ho/edit#heading=h.rxhmi6xlbhyh) to view the design spec.

**Comment by anvithks** [comment]
Started the analysis of the API changes and its impact on the Dashboard.

**Comment by skdwriting** [comment]
What is the update on the analysis and its impact?

**Comment by anvithks** [comment]
Currently the impact is only in the "Create Profile" page where new fields are added. These changes are made locally and I will raise a PR for this shortly after integration testing is done.
The rest of the changes do not impact the Dashboard features directly. I will talk to @PravinRanjan10 and verify this.

**Comment by anvithks** [comment]
PR is raised #208 and is being reviewed.

**Comment by anvithks** [comment]
Integration test needs to be done.

**Comment by anvithks** [comment]
Closing since PR is merged.
