### ISSUE TITLE
GCP display bug

### ISSUE THREAD

**Issue by yuejuSDS** [opensds/opensds-dashboard#283]
![3D538FB4AC3394D5B2397F526B5920A8](https://user-images.githubusercontent.com/45419365/71725451-e74bb480-2e6e-11ea-956f-c83b39d4242b.png)
![$U1B_$GY37Y@)HAM`$GXK%R](https://user-images.githubusercontent.com/45419365/71725501-195d1680-2e6f-11ea-9f2b-a1bd38610ebc.png)

1. GCP is set, but the number of GCP on the home page is still 0

2. The GCP picture is not displayed during migration

**Comment by anvithks** [comment]
Fixed in PR #284
