### ISSUE TITLE
[Design Change] Display cloud provider name under logo on home page.

### ISSUE THREAD

**Issue by anvithks** [opensds/opensds-dashboard#43]
### Current Design:
Currently the home page has four cloud provider logos.  
![home-page-orig-design](https://user-images.githubusercontent.com/19162717/54522630-ba87e880-4993-11e9-93d1-61c9949715ee.png)

1. The cloud providers are not immediately identifiable since the logo does not have the name of the company.  
2. The logos and the source images are of different sizes. The alignment of the logos in side the source image is not consistent.  
3. The Azure logo is still the old one.  
4. The IBM Object storage logo is not legible since the size is small.

### Recommended Changes:

![home-page-design-changes](https://user-images.githubusercontent.com/19162717/54522164-8eb83300-4992-11e9-81ce-50ca0147327a.png)  

![home-page-design-changes-2](https://user-images.githubusercontent.com/19162717/54523920-9da0e480-4996-11e9-8272-f8f4520ff015.png)

1. Keep only the icons of the cloud provider logos and not the name of the company.  Display the cloud provider name as a different element under the cloud.  
2. Unify the size of the cloud provider logos and make them square. Align them to the center of the image.
3. Update the logo to the latest.  
4. Crop the name of the company from the logo and display the name below the cloud.  

Please review.  
I can raise the PR if the changes are approved.

**Comment by anvithks** [comment]
@leonwanghui @xing-yang Please review.

**Comment by leonwanghui** [comment]
I think it should be ok
