### ISSUE TITLE
Infrastructure bar doesn't work any more

### ISSUE THREAD

**Issue by leonwanghui** [opensds/opensds-dashboard#45]
When I installed the latest version of opensds dashboard, I found that after clicking Infrastructure bar, nothing changed and the main menu became empty. 
![捕获](https://user-images.githubusercontent.com/24707117/54667610-ba205680-4b27-11e9-8c01-d959305ae2c2.JPG)

**Comment by leonwanghui** [comment]
@anvithks Could u take a look at this issue? Thanks!

**Comment by anvithks** [comment]
@leonwanghui let me take a look. 
I am not able to reproduce the issue on my setup yet.

**Comment by anvithks** [comment]
@leonwanghui There seems to be some error with the /block/volumes call.  
I will check but may be @jimccfun can take a look. There was a PR addressing some new features in the area.
@leonwanghui was there any change in the API or backend? 

![infra-tab-error](https://user-images.githubusercontent.com/19162717/54736680-4c7d3480-4bd2-11e9-9732-97574bd7934e.png)

**Comment by jimccfun** [comment]
@leonwanghui This bug has been solved, you can close this issue.

**Comment by leonwanghui** [comment]
Resolved by #46
