### ISSUE TITLE
Some issues for non-admin dashboard

### ISSUE THREAD

**Issue by leonwanghui** [opensds/opensds-dashboard#61]
## Problem
When I install an opensds cluster and login in UI with admin role, everything works fine, the dashborad looks like below:
![image](https://user-images.githubusercontent.com/24707117/56494059-a51e5500-6523-11e9-91cc-515c099d066d.png)

But after I created a new user and login with username and password, I can't find any info about profile. 
![image](https://user-images.githubusercontent.com/24707117/56494124-d565f380-6523-11e9-8e1a-00fc1f9f1f5e.png)

## Expect to happen
As a user, I need to see the profile so that I can choose the best one to create the volume.

**Comment by skdwriting** [comment]
@leonwanghui , latest release 0.5.4, can you please test this?

**Comment by leonwanghui** [comment]
@skdwriting It's already fixed for latest code, will close this issue.
