### ISSUE TITLE
Dashboard-Lifecycle: With same name Life cycle rule is getting created.. dashboard behavior abnormal

### ISSUE THREAD

**Issue by satya-gorli** [opensds/opensds-dashboard#88]
1. Click Create button
2. create Life cycle rule
3. Create again with same name
4. Click cancel..
5. It lists 2 rules with same name 
![LifcycleIssues_SameName Lifecycle rule](https://user-images.githubusercontent.com/48289385/59176924-1d92b100-8b78-11e9-9ed9-4b65cee703cf.PNG)

**Comment by anvithks** [comment]
@skdwriting This had a backend fix as well. Probably fixed but need to check.

**Comment by skdwriting** [comment]
@anvithks please verify...
