### ISSUE TITLE
Dashboard-Resource: Create Folder functionality not working

### ISSUE THREAD

**Issue by satya-gorli** [opensds/opensds-dashboard#91]
1. Go to REsource tab
2. in Objects tab, click Create Folder button
3. Provide folder name and click Ok Button
4. Nothing happens.. No success page/message.. No error message/page
![LifcycleIssues_CreateFolderIssue](https://user-images.githubusercontent.com/48289385/59186949-d74a4b80-8b91-11e9-86e3-825eda0bd313.PNG)

**Comment by jimccfun** [comment]
@satya-gorli Which version you used to do this test? I used the latest code of development branch to test, it works fine, please update the code and test. Thank you.

**Comment by satya-gorli** [comment]
Latest Docker Image

**Comment by satya-gorli** [comment]
I used Master not Development branch

**Comment by anvithks** [comment]
@satya-gorli Please check with latest development and let us know if this issue persists.

**Comment by skdwriting** [comment]
@satya-gorli , pls check and confirm

**Comment by satya-gorli** [comment]
Working fine with latest
