### ISSUE TITLE
Some issues in lifecycle configuration

### ISSUE THREAD

**Issue by wisererik** [opensds/opensds-dashboard#94]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
1. I could not edit the days when I add lifecycle rule for an object.
2. My transition target was aws1 backend, but there is obs1 backend when I edit data lifecycle.
3. The layout of select box is not good.

![Selection_001](https://user-images.githubusercontent.com/9572954/59202890-117c1300-8bbb-11e9-8510-37606059babb.png)

4. Layout of transition description should be improved.

![Selection_003](https://user-images.githubusercontent.com/9572954/59210315-f4e7d700-8bca-11e9-8ba6-1db818903659.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Dashboard (release/branch) version:v0.5.3
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wisererik** [comment]
@yuejuSDS Please take a look

**Comment by anvithks** [comment]
@jimccfun Please take a look.

**Comment by skdwriting** [comment]
@wisererik can you please check the RC2 and confirm the issue status?
